export const types = {
  CAPITAL: "CAPITAL",
  INSTALLMENT: "INSTALLMENT",
  PROFIT_RATE: "PROFIT RATE",
  INSTALLMENT_INTERVAL: "INSTALLMENT INTERVAL",
  TAX_RATE: "TAX_RATE",
  GET_PAYMENT: "GET_PAYMENT",
};
